#!/usr/bin/env python3
"""Tests for riptide-review-required workflow detection logic."""

from __future__ import annotations

import os
import sys
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


class TestRiptideReviewDetection:
    """Test the logic for detecting Riptide review comments.

    The workflow checks for:
    - riptide-review[bot] username, OR
    - Riptide-specific markers in body (🤖 Generated by Riptide, ## 🔄, etc.)
    """

    def test_detects_riptide_bot_comment(self):
        """Should detect riptide-review[bot] comments."""
        comment = {"user": {"login": "riptide-review[bot]"}, "body": "TL;DR"}
        assert self._is_riptide_review(comment)

    def test_detects_riptide_markers_in_body(self):
        """Should detect Riptide markers regardless of user."""
        comment = {"user": {"login": "ChonSong"}, "body": "## 🎯 Summary\n\n2 issue(s) found"}
        assert self._is_riptide_review(comment)

    def test_detects_generated_by_riptide(self):
        """Should detect '🤖 Generated by Riptide' marker."""
        comment = {"user": {"login": "ChonSong"}, "body": "🤖 Generated by Riptide · deterministic analysis"}
        assert self._is_riptide_review(comment)

    def test_detects_blast_radius(self):
        """Should detect '📊 Blast Radius' marker."""
        comment = {"user": {"login": "SomeUser"}, "body": "📊 Blast Radius\n6 files, 30 code paths"}
        assert self._is_riptide_review(comment)

    def test_ignores_unrelated_comments(self):
        """Should ignore comments without Riptide markers."""
        comment = {"user": {"login": "RandomUser"}, "body": "Looks good to me!"}
        assert not self._is_riptide_review(comment)

    def test_ignores_coderabbit(self):
        """Should ignore CodeRabbit comments."""
        comment = {"user": {"login": "coderabbitai[bot]"}, "body": "Actionable comments posted: 6"}
        assert not self._is_riptide_review(comment)

    def _is_riptide_review(self, comment: dict) -> bool:
        """Mirror the workflow's detection logic."""
        login = comment["user"]["login"]
        body = comment["body"]

        if login == "riptide-review[bot]":
            return True

        markers = [
            "🤖 Generated by Riptide",
            "## 🔄",
            "Riptide Review",
            "⏱️",
            "📊 Blast Radius",
            "🧠",
            "🎯 Summary",
            "🔍 Findings",
        ]
        return any(marker in body for marker in markers) or "riptide" in body.lower()
